# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
