# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reviews", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="pub_date",
            field=models.DateTimeField(verbose_name="date_published"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
    ]
